### ISSUE TITLE
Suggested / recommended BLE adapter

### ISSUE THREAD

**Issue by techniq** [monteslu/ble-serial#5]
I'm looking to connect to an Arduino running firmata from React-Native using a combination of this project and https://github.com/jacobrosenthal/react-native-ble but I'm having trouble understanding what type of BLE adapter I'll need.

This [project](https://github.com/elin-moco/ble-serialport) seems to require specific hardware (BleShield / Nordic_nRF8001 chip) and adapter a special version of [Firmata](https://codebender.cc/sketch:128276#BLEFirmataSketch.ino).  Are the same required for this project?  I see a lot of mention of the [hm-10](https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=HM-10) chipset, but it's rather confusing which to get (some discuss the firmware on the hm-10 matters, sometimes you get a CC41a instead of hm-10, etc).

Note: I've successfully connected using a JY-MCU bluetooth serial module from my Mac, but from my understanding Bluetooth and BLE are only related in name (much like Java/Javascript).  I'm also struggling to understand how to connect to the JY-MCU module from React Native (I left an issue on another project - https://github.com/rusel1989/react-native-bluetooth-serial/issues/11) and thus thought BLE was the way to go (once I get the proper hardware module).

Thanks.

**Comment by jacobrosenthal** [comment]
Hey. ble-serial project uses [noble](https://github.com/sandeepmistry/noble/) under the hood so it draws its requirements from there. The question is really what are you running this on, a pi or a mac or something else?

**Comment by techniq** [comment]
Thanks @jacobrosenthal.  I'm currently using a Mac, but the plan is to connect using React Native from Android and iOS.  I decided to pick up Adafruit's [Bluefruit LE UART Friend](https://www.adafruit.com/product/2479) which is based on the MDBT40/nRF51822.  I'm going to experiment and will report back any issues I come across.

**Comment by techniq** [comment]
@jacobrosenthal so far I've been [struggling](https://github.com/adafruit/Adafruit_BLE_PinIO/issues/10) to get the UART Friend to work.  Could you by chance tell me which BLE module you are using (and Arduino variant)?  I don't know if my issues stem from using a Nano (although it works fine over USB and using a Bluetooth Classic JY-MCU) but I'm sure struggling getting BLE to work.  Thanks

**Comment by jacobrosenthal** [comment]
For a ble central i use the internal mac ble hardware. For ble peripheral I use everything.

You need to break down your problem a bit. See if bluetooth on your mac works to connect to some known good device, see if your mac/phone can see your bluetooth device with an app like like lightblue, then see if noble can scan/connect to your device, then finally when you know the entire stack works you can add the last abstraction layer of something like firmata/ble-serial etc.

**Comment by techniq** [comment]
@jacobrosenthal Thanks.  I'm able to connect successfully to various ble peripherals, including a bb-8 sphero which I've controlled using a node library as well.  I'm also able to connect to the Bluefruit LE UART Friend (the connected blue LED lights up, and it shows connected on the Mac).   I have a late-2011 MacBook Pro and thus have to use a [USB adapter](https://www.amazon.com/gp/product/B00HQCINKE/ref=oh_aui_search_detailpage?ie=UTF8&psc=1) 

It appears I'm sending and receiving data over the BLE connection (expand the logs on [this issue](https://github.com/monteslu/ble-serial/issues/6)) but firmata.js/johnny five never emits the ready event.
```
  ble-serial writing <Buffer f9> +4s
  ble-serial writing <Buffer f0 79 f7> +1ms
  ble-serial read <Buffer f9 02 03> true +86ms
```

I don't know if the issue is now beyond ble-serial and with firmata.js, although I was trying to get [this example](https://github.com/monteslu/ble-serial/blob/master/example/firmataExample.js) from ble-serial to work and so far I've not had any success.

**Comment by techniq** [comment]
I was [successfully](https://github.com/monteslu/ble-serial/issues/6) after changing the baudrate to 57600 using `AT+BAUDRATE=57600` in command mode.  Closing this issue as well.
